# baseURL = "localhost:1313"
baseURL = ""
languageCode = "en-us"
title = "Adi Nugroho"
theme = "hugo-lodi-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#574CDD"
    description = "Portfolio of Adi Nugroho"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "hidrodixtion@gmail.com"
    # facebook = "lex.collado"
    twitter = "adinugroho"
    # dribbble = "alexiscollado"
    linkedin = "https://www.linkedin.com/in/anugroho"
    medium = "adinugroho"

[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "avatar.jpg"
    subtitle = "Hi! I'm Adi Nugroho, a Mobile Engineer Expert from Indonesia."
    hero_right = ["**Currently Doing Mobile App Development (Freelance).**", "Proven Software Developer with experiences on enterprise & startup scale. Love innovations & make an impact through Software. Happy to see happy clients & users.", "Since 2012, I've been focusing on Native Mobile App development for both iOS and Android. My skillsets including **Native iOS** (Swift), **Native** Android (Java & Kotlin), **Flutter**, **Web Development** (NodeJS & Ruby on Rails), **Database** & **Git**. Beside writing codes, I also do a bit of writing [on Medium](https://medium.com/@adinugroho/), mostly about programming.", "I finished my Bachelor's degree in Computer Science at Sepuluh Nopember Insitute of Technology, graduated in 2009."]
    resume = "ResumeCollado.pdf"

[params.process]
    enable = false
    title = "My Process"
    subtitle = "Full Process Design"

[params.case_studies]
    enable = false
    title = "Projects"
    subtitle = "Selected Works"

[params.footer]
    enable = true
